server:
  port: 9001
spring:
  application:
    name: microservice-user
  datasource:
    url: jdbc:mysql://localhost:3306/jasonlearn?characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
  instance:
    prefer-ip-address: true
#    lease-expiration-duration-in-seconds: 90
#    lease-renewal-interval-in-seconds: 30

